/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = string;
export type NoName2 = string;
export type NoName3 = string;
export type NoName4 = string;
export type NoName = {
  name: NoName1;
  appId: NoName2;
  targetField: NoName3;
  prefix: NoName4;
}[];

export interface ConfigSchema {
  settings: NoName;
}
